version: '3.8'

services:
  jekyll:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: jekyll-preview
    ports:
      - "4000:4000"     # Jekyll site
      - "35729:35729"   # LiveReload
    volumes:
      - ..:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: sh -c "bundle install && jekyll serve --host 0.0.0.0 --livereload --force_polling"
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
